name: crime-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # notebook/dev
  - jupyterlab
  - ipykernel

  # data + viz
  - pandas
  - numpy
  - altair
  - plotly


  - pyarrow

  # app
  - pip:
      - shiny>=1.5
      - shinywidgets>=0.7
      - shinychat>=0.2
      - vegafusion>=2.0.3
      - vegafusion-python-embed>=1.0.0
      - vl-convert-python>=1.8.0
